### ISSUE TITLE
Change package name from "flutter_timezone" to "flutter_native_timezone"

### ISSUE THREAD

**Issue by Akiyamka** [tjarvstrand/flutter_timezone#11]
My dependencies want to use flutter_native_timezone that not supported anymore.
For fix that it possible to use next trick:

```
dependency_overrides:
  flutter_native_timezone:
    git:
      url: https://github.com/tjarvstrand/flutter_timezone
```

but unfortunately it require same name as forked package
```
Resolving dependencies... 
Error on line 1, column 7: "name" field doesn't match expected name "flutter_native_timezone".
```
